import React from "react";
import { Link } from "react-router-dom";
import Footer from "../footer/Footer";
const TermsAndConditions = () =>{
    return(
        <section>
        <div className="parent">
        <div className="fill1">
        <img className="image1" style={{width:"100%"}} src="terms.svg"/>
        </div>
        <Link to="/home"><img className="image2" src="logo.svg"/></Link>
        <div className="famto" style={{fontSize:"20px", fontFamily:"Poppins"}}>Terms and Conditions</div>
        </div><br/>
        <section style={{width:"100%"}}>
        <div style={{marginLeft:"60px", maxWidth:"100vw", marginRight:"50px"}}>        
        <h3 style={{textAlign:"left"}}>General Terms</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        By accessing and placing an order with Famto , you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Famto.
        </p>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Under no circumstances shall Famto team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if Famto team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data,you assume any costs thereof.
        </p>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Famto will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy at any moment.
        </p>
        <h3 style={{textAlign:"left"}}>License</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Famto grants, you a revocable, non-exclusive, non- transferable, limited license to download, install and use the Famto strictly in accordance with the terms of this Agreement.
        </p>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        These Terms & Conditions are a contract between you and Famto (referred to in these Terms & Conditions as "Company", "us", "we" or "our"), the provider of the Famto website and the services accessible from the Famto  website (which are collectively referred to in these Terms & Conditions as the "Famto Service"). 
        </p>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the Famto Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.
        </p>
        <h3 style={{textAlign:"left"}}>Definitions and key terms</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, are strictly defined as:
        </p>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        <ul>
        <li>
        Cookie: Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you such as your language preference or login information.
        </li>
        <li>
        Company: When these terms mention "Company, "we," "us," or "our," it refers to Famto . Famto that is responsible for your information under these Terms & Conditions.
        </li>
        <li>
        Country: Where Famto or the owners/founders of Famto are based, in this case is Famto_
        </li>
        <li>
        Device: Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Famto and use the services.
        </li>
        <li>
        Service: This refers to the service provided by Famto as described in the relative terms (if available) and on this platform.
        </li>
        <li>
        Third-party service: This refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
        </li>
        <li>
        Website: Famto site, which can be accessed via this URL: www.famto.in
        </li>
        <li>
        You: A person or entity that is registered with Famto to use the services
        </li>
        </ul>
        </p>
        <h3 style={{textAlign:"left"}}>Restrictions</h3>        
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
         You agree not to, and you will not permit others to: 
         <ul>
         <li>
        License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the Famto or make the platform available to any third party.
        </li>
        <li>
        Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse  engineer any part of the Famto. 
        </li>
        <li>
        Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of or its affiliates, partners, suppliers or the licensors of the Famto.
        </li>
        </ul>
        </p>
        <h3 style={{textAlign:"left"}}>Payment</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        If you register to any of our recurring payment plans, you agree to pay all fees or charges to your account for the Service in accordance with the fees, charges and billing terms in effect at the time that each fee or charge is due and payable. Unless otherwise indicated in an order form, you must Provide Famto with a valid credit card (Visa, MasterCard, or any other issuer accepted by us) ("Payment Provider") as a condition to signing up for the Premium plan. Your Payment Provider agreement governs your use of the designated credit card account, and you must refer to that agreement and not these Terms to determine your rights and liabilities with respect to your Payment Provider. By providing Famto with your credit card number and associated payment information, you agree that Famto is authorized to verify information immediately, and subsequently invoice your account for all fees and charges due and payable to Famto here under and that no additional notice or consent is required. You agree to immediately notify Famto of any change in your billing address or the credit card used for payment hereunder. 
        <br/>
        <ul>
        <li>
        Famto reserves the right at any time to change its prices and billing methods, either immediately upon posting on our Site or by e-mail delivery to your organization's administrator(s).
        </li>
        <li>
        Any attorney fees, court costs, or other costs incurred in collection of delinquent undisputed amounts shall be the responsibility of and paid for by you. 
        </li>
        <li>
        No contract will exist between you and Famto for the Service until Famto accepts your order by a confirmatory e-mail, SMS/MMS message, or other appropriate means of communication. 
        </li>
        <li>
        You are responsible for any third-party fees that you may incur when using the Service.
        </li>
        </ul>
        </p>
        <h3 style={{textAlign:"left"}}>Return and Refund Policy</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Thanks for shopping at Famto. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you're exploring, evaluating, and purchasing our products. As with any shopping experience, there are terms and conditions that apply to transactions at Famto We'll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at Famto .you agree to the terms along with Famto's Privacy Policy. If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any of the issues you are going through with our Product.and Refund Policy.
        </p>
        <h3 style={{textAlign:"left"}}>Your Suggestions</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to Famto with respect to the Famto shall remain the sole and exclusive property of Famto. Famto shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.
        </p>
        <h3 style={{textAlign:"left"}}>Your Consent</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our Famto. Registering an account, or making a purchase, you hereby consent to our Terms & Conditions.    
        </p>
        <h3 style={{textAlign:"left"}}>Links to Other Websites</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        These Terms & Conditions apply only to the Services. The Services may contain links to other websites not operated or controlled by Famto. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Terms & Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website's own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.   
        </p>
        <h3 style={{textAlign:"left"}}>Cookies</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Famto uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our Famto but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the Famto as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.    
        </p>
        <h3 style={{textAlign:"left"}}>Changes To Our Terms & Conditions</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        You acknowledge and agree that Famto may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at Famto's sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform Famto when you stop using the service. You acknowledge and agree that if Famto disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which are contained in your account. If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.
        </p>
        <h3 style={{textAlign:"left"}}>Modification To Our Famto</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Famto reserves the right to modify, suspend or discontinue, temporarily or permanently,the Famto or any service to which it connects, with or without notice and without liability to you.
        </p>
        <h3 style={{textAlign:"left"}}>Updates To Our Famto</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Famto may from time to time provide enhancements or improvements to the features/functionality of the Famto which may include patches, bug fixes, updates, upgrades and other modifications ("Updates"). Updates may modify or delete certain features and/or functionalities of the Famto. You agree that Famto has no obligation to (i) provide any Updates, or (i continue to provide or enable any particular features and/or functionalities of the Famto to you. You further agree that all Updates will be () deemed to constitute an integral part of the Famto, and (i) subject to the terms and conditions of this Agreement.
        </p>
        <h3 style={{textAlign:"left"}}>Third-Party Services</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        We may display, include or make available third-party content including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services"). You acknowledge and agree that Famto shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Famto does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services. Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.
        </p>
        <h3 style={{textAlign:"left"}}>Terms and Termination</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        This Agreement shall remain in effect until terminated by you or Famto. Famto may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice. This Agreement will terminate immediately, without prior notice from Famto in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the Famto and all copies thereof from your computer. Upon termination of this Agreement, you shall cease all use of the Famto and delete all copies of the Famto from your computer. Termination of this Agreement will not limit any of Famto's rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.
        </p>
        <h3 style={{textAlign:"left"}}>Copyright infringement Notice</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        If you are a copyright owner or such owner's agent and believe any material on our Famto constitutes an infringement on your copyright, please contact us setting forth the following information: (a) a physical or electronic signature of the copyright owner or a person authorized to act on his behalf; (b) identification of the material that is claimed to be infringing; (c) your contact information, including your address, telephone number, and an email; (d) a statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and (e) the a statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on behalf of the owner.
        </p>
        <h3 style={{textAlign:"left"}}>Indemnification</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        You agree to indemnify and hold Famto and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand,including reasonable attorneys' fees, due to or arising out of your: (a) use of the Famto; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.
        </p>
        <h3 style={{textAlign:"left"}}>No Warranties</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        The Famto is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, Famto on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the Famto, including all implied warranties of merchantability, fitness for a particular purpose, title and non- infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. 
        </p>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Without limitation to the foregoing,Famto provides no warranty or undertaking, and makes no representation of any kind that the Famto will meet your requirements, achieve any intended results, be compatible or work with any other software, websites, systems or services,operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected. Without limiting the foregoing, neither Famto nor any. Famto provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Famto,or the information, content, and materials or products included thereon;(ii) that the Famto will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the Famto or (iv) that the Famto, its servers, the content, or e-mails sent from or on behalf of Famto are free of viruses, scripts, Trojan horses, worms, malware, time bombs or other harmful components. 
        </p>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.
        </p>
        <h3 style={{textAlign:"left"}}>Limitation of Liability</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Not withstanding any damages that you might incur, the entire liability of Famto and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the Famto. 
        </p>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        To the maximum extent permitted by applicable law, in no event shall Famto or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the Famto ,third-party software and/or third-party hardware used with the Famto, or otherwise in connection with any provision of this Agreement),even if Famto or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose. 
        </p>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.
        </p>
        <h3 style={{textAlign:"left"}}>Severability</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect. 
        </p>
       <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        This Agreement, together with the Privacy Policy and any other legal notices published by Famto on the Services, shall constitute the entire agreement between you and Famto concerning the Services. If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and Famto's failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision. YOU AND Famto_AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE,SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.
        </p>
        <h3 style={{textAlign:"left"}}>Waiver</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not affect a party's ability to exercise such right or require such performance at any time thereafter nor shall the waiver of a breach constitute waiver of any subsequent breach. 
       </p>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        No failure to exercise, and no delay in exercising, on the part of either party, any right or any power under this Agreement shall operate as a waiver of that right or power. Nor shall any single or partial exercise of any right or power under this Agreement preclude further exercise of that or any other right granted herein. In the event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this Agreement shall govern.
        </p>
        <h3 style={{textAlign:"left"}}>Amendments to this agreement</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Famto reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Famto after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Famto.
        </p>
        <h3 style={{textAlign:"left"}}>EntireAgreement</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        The Agreement constitutes the entire agreement between you and Famto regarding your use of the Famto and supersedes all prior and contemporaneous written or oral agreements between you and Famto. You may be subject to additional terms and conditions that apply when you use or purchase other Famto's services, which Famto will provide to you at the time of such use or purchase.
        </p>
        <h3 style={{textAlign:"left"}}>Updates to Our Terms</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        We may change our Service and policies, and we may need to make changes to these Terms so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to these Terms and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Terms. If you do not want to agree to these or any updated Terms, you can delete your account.
        </p>
        <h3 style={{textAlign:"left"}}>Intellectual Property</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        The Famto and its entire contents, features and functionality including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by Famto,, its licensors or other providers of such material and are protected by Famto and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. The material may not be copied, modified, reproduced, downloaded or distributed in any way, in whole or in part, without the express prior written permission of Famto, unless and except as is expressly provided in these Terms & Conditions. Any unauthorized use of the material is prohibited.
        </p>
        <h3 style={{textAlign:"left"}}>Agreement to Arbitate</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        This section applies to any dispute EXCEPT IT DOESN'T INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR OR FAMTO'S INTELLECTUAL PROPERTY RIGHTS. 
        </p><p style={{textAlign:"left", fontFamily:"Poppins"}}>
        The term"dispute" means any dispute, action, or other controversy between you and Famto concerning the Services or this agreement, whether in contract, warranty, tort, statute, regulation,ordinance, or any other legal or equitable basis. "Dispute" will be given the broadest possible meaning allowable under law.
        </p>
        <h3 style={{textAlign:"left"}}>Notice to Dispute</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        In the event of a dispute, you or Famto must give the other a Notice of Dispute, which is a written statement that sets forth the name, address, and contact information of the party giving it, the facts giving rise to the dispute, and the relief requested. You must send any Notice of Dispute via email to: Famto will send any Notice of Dispute to you by mail to your address if we have it, or otherwise to your email address. You and Famto will attempt to resolve any dispute through informal negotiation within sixty (60) days from the date the Notice of Dispute is sent. After sixty (60) days, you or Famto may commence arbitration.
        </p>
        <h3 style={{textAlign:"left"}}>Binding Arbitration</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        If you and Famto don't resolve any dispute by informal negotiation, any other effort to resolve the dispute will be conducted exclusively by binding arbitration as described in this section. You are giving up the right to litigate (or participate in as a party or class member) all disputes in court before a judge or jury. The dispute shall be settled by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association. Either party may seek any interim or preliminary injunctive relief from any court of competent jurisdiction, as necessary to protect the party's rights or property pending the completion of arbitration. Any and all legal, accounting, and other costs, fees, and expenses incurred by the prevailing party shall be borne by the non-prevailing party.
        </p>
        <h3 style={{textAlign:"left"}}Submissions and Privacy></h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        In the event that you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data or proposals, including ideas for new or improved products, services, features, technologies or promotions, you expressly agree that such submissions will automatically be treated as non- confidential and non-proprietary and will become the sole property of Famto without any compensation or credit to you whatsoever. Famto and its affiliates shall have no obligations with respect to such submissions or posts and may use the ideas contained in such submissions or posts for any purposes in any medium in perpetuity, including, but not limited to, developing, manufacturing, and marketing products and services using such ideas.
        </p>
        <h3 style={{textAlign:"left"}}>Promotions</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Famto may, from time to time, include contests, promotions, sweepstakes, or other activities ("Promotions") that require you to submit material or information concerning yourself. Please note that all Promotions may be governed by separate rules that may contain certain eligibility requirements, such as restrictions as to age and geographic location. You are responsible to read all Promotions rules to determine whether or not you are eligible to participate. If you enter any Promotion, you agree to abide by and to comply with all Promotions Rules. Additional terms and conditions may apply to purchases of goods or services on or through the Services, which terms and conditions are made a part of this Agreement by this reference.
        </p>
        <h3 style={{textAlign:"left"}}>Typographical Errors</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        In the event a product and/or service is listed at an incorrect price or with incorrect information due to typographical error, we shall have the right to refuse or cancel any orders placed for the product and/ or service listed at the incorrect price. We shall have the right to refuse or cancel any such order whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is canceled, we shall immediately issue a credit to your credit card account or other payment account in the amount of the charge.
        </p>
        <h3 style={{textAlign:"left"}}>Miscellaneous</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        If for any reason a court of competent jurisdiction finds any provision or portion of these Terms & Conditions to be unenforceable, the remainder of these Terms & Conditions will continue in full force and effect. Any waiver of any provision of these Terms & Conditions will be effective only if in writing and signed by an authorized representative of Famto, Famto will be entitled to injunctive or other equitable relief (without the obligations of posting any bond or surety) in the event of any breach or anticipatory breach by you. Famto operates and controls the Famto Service from its offices in Famto . The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation. Accordingly, those persons who choose to access the Famto Service from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.These Terms & Conditions (which include and incorporate the Famto Privacy Policy) contains the entire understanding, and supersedes all prior understandings, between you and concerning its subject matter, and cannot be changed or modified by you. The section headings used in this Agreement are for convenience only and will not be given any legal import.
        </p>
        <h3 style={{textAlign:"left"}}>Disclaimer</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Famto is not responsible for any content, code or any other imprecision. Famto does not provide warranties or guarantees. In no event shall Famto be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. Famto reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice. The Famto Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. Famto is a distributor and not a publisher of the content supplied by third parties; as such,Famto exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the Famto Service. Without limiting the foregoing, Famto specifically disclaims all warranties and representations in any content transmitted on or in connection with the Famto Service or on sites that may appear as links on the Famto Service, or in the products provided as a part of, or otherwise in connection with, the Famto Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by Famto or any of its affiliates, employees, officers,directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, Famto does not warrant that the Famto Famto_Service will be uninterrupted, uncorrupted, timely, or error-free.
        </p>
        <h3 style={{textAlign:"left"}}>Contact Us</h3>
        <p style={{textAlign:"left", fontFamily:"Poppins"}}>
        Don't hesitate to contact us if you have any questions.<br/>
        via email:<strong><a href="mailto:contact@famto.in">contact@famto.in</a></strong><br/>
        via phone:<span style={{fontWeight:"bold", color:"black"}}>+91 97781 80794</span><br/>
        via link: <strong><a href="http://www.famto.in">www.famto.in</a></strong>
         </p>
      
         
        
        
        
       </div>  <br/>
       <Footer />
       </section>
        </section>
    );
};
export default TermsAndConditions;